// GFX Font: EnvyBlocks
// Range: U+2580 - U+259F at 8px
// Generated by ttf2gfx.py
// Approx. 329 bytes

#pragma once

const uint8_t EnvyBlocksBitmaps[] PROGMEM = {
  0xF7, 0xFF, 0xFF, 0xF8, 0xF7, 0xC0, 0xF7, 0xFE, 0xF7, 0xFF, 0xF0, 0xF7, 
  0xFF, 0xFF, 0x80, 0xFF, 0xFF, 0xFF, 0xFC, 0xFF, 0xFF, 0xFF, 0xFF, 0xE0, 
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xF7, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xEF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 
  0xFF, 0xFC, 0xFF, 0xFF, 0xF0, 0xFF, 0xFF, 0xF0, 0xFF, 0xC0, 0xFF, 0x80, 
  0xDF, 0xFF, 0xFF, 0xFC, 0xA5, 0xA5, 0xA0, 0x5A, 0x50, 0xF7, 0xBD, 0xEF, 
  0x7B, 0xFE, 0xF8, 0x57, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0xF7, 0xC0, 
  0xFF, 0x80, 0xFF, 0xC0, 0xDF, 0xFE, 0xFF, 0xF0, 0xC6, 0x31, 0x8C, 0x7B, 
  0xFF, 0xFF, 0xC0, 0xC6, 0x31, 0x8C, 0x78, 0xE7, 0x39, 0xC0, 0xF7, 0xFF, 
  0xFF, 0xFB, 0x18, 0xC6, 0x00, 0xF7, 0xFF, 0xFF, 0xFC, 0xE7, 0x39, 0xC0, 
  0xDF, 0xFE, 0x80, 0x31, 0xCE, 0x73, 0xFB, 0x18, 0xC6, 0x00, 0x31, 0xCE, 
  0x73, 0xFF, 0xFF, 0xFF, 0xC0
};

const GFXglyph EnvyBlocksGlyphs[] PROGMEM = {
  {      0,   5,   6,   4,    0,    0 },  // U+2580 '▀'
  {      4,   5,   2,   4,    0,    8 },  // U+2581 '▁'
  {      6,   5,   3,   4,    0,    7 },  // U+2582 '▂'
  {      8,   5,   4,   4,    0,    6 },  // U+2583 '▃'
  {     11,   5,   5,   4,    0,    5 },  // U+2584 '▄'
  {     15,   5,   6,   4,    0,    4 },  // U+2585 '▅'
  {     19,   5,   7,   4,    0,    3 },  // U+2586 '▆'
  {     24,   5,   8,   4,    0,    2 },  // U+2587 '▇'
  {     29,   5,  10,   4,    0,    0 },  // U+2588 '█'
  {     36,   4,  10,   4,    0,    0 },  // U+2589 '▉'
  {     41,   4,  10,   4,    0,    0 },  // U+258A '▊'
  {     46,   3,  10,   4,    0,    0 },  // U+258B '▋'
  {     50,   2,  10,   4,    0,    0 },  // U+258C '▌'
  {     53,   2,  10,   4,    0,    0 },  // U+258D '▍'
  {     56,   1,  10,   4,    0,    0 },  // U+258E '▎'
  {     58,   1,   9,   4,    0,    1 },  // U+258F '▏'
  {     60,   3,  10,   4,    2,    0 },  // U+2590 '▐'
  {     64,   4,   9,   4,    0,    1 },  // U+2591 '░'
  {     69,   5,   9,   4,    0,    1 },  // U+2592 '▒'
  {     75,   5,  10,   4,    0,    0 },  // U+2593 '▓'
  {     82,   5,   2,   4,    0,    0 },  // U+2594 '▔'
  {     84,   1,   9,   4,    4,    1 },  // U+2595 '▕'
  {     86,   2,   5,   4,    0,    5 },  // U+2596 '▖'
  {     88,   3,   5,   4,    2,    5 },  // U+2597 '▗'
  {     90,   2,   6,   4,    0,    0 },  // U+2598 '▘'
  {     92,   5,  10,   4,    0,    0 },  // U+2599 '▙'
  {     99,   5,  10,   4,    0,    0 },  // U+259A '▚'
  {    106,   5,  10,   4,    0,    0 },  // U+259B '▛'
  {    113,   5,  10,   4,    0,    0 },  // U+259C '▜'
  {    120,   3,   6,   4,    2,    0 },  // U+259D '▝'
  {    123,   5,  10,   4,    0,    0 },  // U+259E '▞'
  {    130,   5,  10,   4,    0,    0 }  // U+259F '▟'
};

const GFXfont EnvyBlocks PROGMEM = {
  (uint8_t  *)EnvyBlocksBitmaps,
  (GFXglyph *)EnvyBlocksGlyphs,
  0x2580,  // first
  0x259F,  // last
  12         // yAdvance
};
