// GFX Font: IosevkaBlocks
// Range: U+2580 - U+259F at 8px
// Generated by ttf2gfx.py
// Approx. 312 bytes

#pragma once

const uint8_t IosevkaBlocksBitmaps[] PROGMEM = {
  0xFF, 0xFF, 0xFF, 0xF0, 0xFF, 0xF0, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xF0, 0xFF, 0xFF, 0xFF, 0xFF, 
  0xFF, 0xF0, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xF0, 0xFF, 0xFF, 0xFF, 0xFF, 0xF0, 
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xF0, 0xFF, 0xF0, 0xFF, 0xFF, 
  0xFF, 0x81, 0x12, 0x24, 0xA8, 0x1A, 0x10, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 
  0xFF, 0xF0, 0xFF, 0xF0, 0xFF, 0xF0, 0xFF, 0xF0, 0xFF, 0xF0, 0xCC, 0xCC, 
  0xCC, 0xFF, 0xFF, 0xFF, 0xCC, 0xCC, 0xCC, 0x33, 0x33, 0x33, 0xFF, 0xFF, 
  0xFF, 0xCC, 0xCC, 0xCC, 0xFF, 0xFF, 0xFF, 0x33, 0x33, 0x33, 0xFF, 0xF0, 
  0x33, 0x33, 0x33, 0xCC, 0xCC, 0xCC, 0x33, 0x33, 0x33, 0xFF, 0xFF, 0xFF
};

const GFXglyph IosevkaBlocksGlyphs[] PROGMEM = {
  {      0,   4,   6,   4,    0,   -1 },  // U+2580 '▀'
  {      3,   4,   1,   4,    0,    9 },  // U+2581 '▁'
  {      4,   4,   3,   4,    0,    8 },  // U+2582 '▂'
  {      6,   4,   4,   4,    0,    7 },  // U+2583 '▃'
  {      8,   4,   6,   4,    0,    5 },  // U+2584 '▄'
  {     11,   4,   8,   4,    0,    3 },  // U+2585 '▅'
  {     15,   4,   9,   4,    0,    2 },  // U+2586 '▆'
  {     20,   4,  11,   4,    0,    0 },  // U+2587 '▇'
  {     26,   4,  12,   4,    0,   -1 },  // U+2588 '█'
  {     32,   4,  12,   4,    0,   -1 },  // U+2589 '▉'
  {     38,   3,  12,   4,    0,   -1 },  // U+258A '▊'
  {     43,   3,  12,   4,    0,   -1 },  // U+258B '▋'
  {     48,   2,  12,   4,    0,   -1 },  // U+258C '▌'
  {     51,   2,  12,   4,    0,   -1 },  // U+258D '▍'
  {     54,   1,  12,   4,    0,   -1 },  // U+258E '▎'
  {     56,   1,  12,   4,    0,   -1 },  // U+258F '▏'
  {     58,   2,  12,   4,    2,   -1 },  // U+2590 '▐'
  {     61,   0,   0,   8,    0,    0 },  // U+2591 '░'
  {     61,   4,  11,   4,    0,   -1 },  // U+2592 '▒'
  {     67,   4,  12,   4,    0,   -1 },  // U+2593 '▓'
  {     73,   4,   1,   4,    0,   -1 },  // U+2594 '▔'
  {     74,   1,  12,   4,    3,   -1 },  // U+2595 '▕'
  {     76,   2,   6,   4,    0,    5 },  // U+2596 '▖'
  {     78,   2,   6,   4,    2,    5 },  // U+2597 '▗'
  {     80,   2,   6,   4,    0,   -1 },  // U+2598 '▘'
  {     82,   4,  12,   4,    0,   -1 },  // U+2599 '▙'
  {     88,   4,  12,   4,    0,   -1 },  // U+259A '▚'
  {     94,   4,  12,   4,    0,   -1 },  // U+259B '▛'
  {    100,   4,  12,   4,    0,   -1 },  // U+259C '▜'
  {    106,   2,   6,   4,    2,   -1 },  // U+259D '▝'
  {    108,   4,  12,   4,    0,   -1 },  // U+259E '▞'
  {    114,   4,  12,   4,    0,   -1 }  // U+259F '▟'
};

const GFXfont IosevkaBlocks PROGMEM = {
  (uint8_t  *)IosevkaBlocksBitmaps,
  (GFXglyph *)IosevkaBlocksGlyphs,
  0x2580,  // first
  0x259F,  // last
  12         // yAdvance
};
